services:
  postgresql:
    image: postgres:13.4-buster
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carroteats
    ports: ['5432:5432'] 
