services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000

  prometheus:
    image: prom/prometheus

    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:password@postgresql:5432/carroteats?sslmode=disable"
    links:
      - postgresql
      - prometheus

  postgresql:
    image: postgres:13.4-buster
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./init/init_tables.sql:/docker-entrypoint-initdb.d/init_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carroteats
    ports: ['5432:5432']
